name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup SourcePawn Compiler
      uses: rumblefrog/setup-sp@v1.0.0
    - name: Prepare publish
      run: |
        pwsh prepare-publish.ps1
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: ftp-files
        # Directory containing files to upload
        path: dist/ftp/
  
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download files
        uses: actions/download-artifact@v1.0.0
        with:
          # Artifact name
          name: ftp-files
          # Destination path
          path: ftp/
      - name: Upload to FTP
        working-directory: ftp
        run: |
          find . -type f -exec curl -u krus.dk:${{ secrets.FTP_KRUSDK_PASSWORD }} --ftp-create-dirs -T {} ftp://krus.dk/sourcemod/{} \;
