name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        ls
    - name: Setup SourcePawn Compiler
      uses: rumblefrog/setup-sp@v1.0.0
    - name: Test compiler
      run: |
        cd AFK
        spcomp afk.sp -i "../includes" -w217 
    - name: Final script
      run: echo All done
